name: End-to-end tests and deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes Cypress
        uses: cypress-io/github-action@v6
        with:
          command: npm run test

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./